### ISSUE TITLE
CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by tomanick** [mit-han-lab/spvnas#92]
When I wanted to run train.py file, I got this error.
<img width="800" alt="cuda_error" src="https://user-images.githubusercontent.com/37836335/168573400-c6a55deb-eba9-479b-94c0-53276ea8c231.png">

Does anybody know how to solve this problem?

Environment:
python: 3.7
pytorch: 1.10.1
Cuda: 11.3
Cudnn: 8.2.1

**Comment by CCInc** [comment]
Hi @tomanick , what GPU / compute capability are you trying to run on?

**Comment by tomanick** [comment]
@CCInc , NVIDIA Geforce RTX 3080Ti

**Comment by tomanick** [comment]
I guessed that perhaps this problem had something to do with OOM.
Afterwards, I found that my input data format of point clouds was [xyz, pc numbers] which was the input format of pvcnn. 
The point clouds format for sparse_quantize of spvcnn is [pc numbers, xyz]. 
When I changed the order of point cloud data, the problem was solved.
Thanks!
